### ISSUE TITLE
Update README clean task example to return del or use rimraf instead

### ISSUE THREAD

**Issue by wagerfield** [ziflex/gulp-tasks-monorepo#5]
The example in the repo doesn't work since `del` doesn't have a completion callback as a second arg—it returns a promise instead. 

The `clean` task should be like this:

```js
repo.task('clean', function clean(pkg) {
  gutil.log('Cleaning', pkg.name(), 'package');

  return del(path.join(pkg.location(), '/dist'));
});
```

...though I appreciate that you are trying to demo the use of the `done` callback, so perhaps replace `del` in the example with `rimraf` that has the signature `rimraf(f, [opts], callback)`.

```js
repo.task('clean', function clean(pkg, done) {
  gutil.log('Cleaning', pkg.name(), 'package');

  rimraf(path.join(pkg.location(), '/dist'), done);
});
```

**Comment by ziflex** [comment]
Good point, thanks!
