### ISSUE TITLE
0.3.0 doesn't have updates published

### ISSUE THREAD

**Issue by wagerfield** [ziflex/gulp-tasks-monorepo#6]
Issue #4 hasn't been resolved with the `0.3.0` published update. Looking at the diff from the commit, you removed the `prepublish` script that builds the project:

https://github.com/ziflex/gulp-tasks-monorepo/commit/8da12fe90141ea5e2e272ace5fd2170d995d146f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L13

I expect you forgot to build the project ahead of publishing to npm, since after updating my package locally, the options object isn't being passed to `Logger`:

```js
var Manager = function () {
    function Manager() {
        _classCallCheck(this, Manager);

        var options = _options2.default.apply(undefined, arguments);

        this[FIELDS.logger] = (0, _logger2.default)(); // options is not being passed
        this[FIELDS.packages] = (0, _manager2.default)(this[FIELDS.logger], options.packages);
        this[FIELDS.tasks] = (0, _manager4.default)(this[FIELDS.logger], this[FIELDS.packages], options.tasks);
    }
```

Please could you build the project and publish to npm? Perhaps add the `prepublish` script back to save this from happening again :)

**Comment by ziflex** [comment]
Oh crap. Sorry for that.
I just came back from vacation, need some time to get into the flow :)

**Comment by wagerfield** [comment]
No worries at all, thanks for publishing the updates :)
